### ISSUE TITLE
RFID Card Reader Model

### ISSUE THREAD

**Issue by xdnewlun1** [evildaemond/doorsim#1]
Sorry If I missed this in the README but what RFID card reader was used for this project? I am gathering a list of what I need to purchase and want to make sure I get the right thing. I dont see any specific model mentioned in the build instructions, just a vague reference to RFID reader.

Thank you in advanced.

**Comment by evildaemond** [comment]
Hey there, 

You can use any RFID reader which outputs in wiegand format. The 3D printed cases are designed for multiple types of RFID Reader profiles, the major vendor dimensions, but the handheld can use any of them.
